# Generated by Django 5.2.16 on 2026-08-07 04:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0006_brand_category_customer_order'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
    ]
